Log output and print command as string on error when invoking external commands
When a command fails to execute, its args are shown in the slice syntax
which makes it cumbersome to copy&paste said command for further
analysis, e.g.

    Error: Unable to install Cilium:  unable to execute "az [aks show --resource-group foo-test-12960 --name foo-test-12960]": exit status 3

Change the command args to be printed as a space separated string, so
they can be easily copy&pasted from the error message:

    Error: Unable to install Cilium: unable to execute "az aks show --resource-group foo-test-12960 --name foo-test-12960": exit status 3

Also consistently log the stdout/stderr of the invoked command on error.

Co-authored-by: Thomas Graf <thomas@cilium.io>
Signed-off-by: Tobias Klauser <tobias@cilium.io>